services:

  pg:
    image: postgres:15
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'warehouse']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: